name = "Classic ASP"
grammar = "embedded_template"
path_suffixes = ["asp", "asa", "inc"]
autoclose_before = ">})"
wrap_characters = { start_prefix = "<", start_suffix = ">", end_prefix = "</", end_suffix = ">" }
brackets = [
    { start = "<%", end = " %>", close = true, newline = true },
    { start = "<!--", end = " -->", close = true, newline = true },
    { start = "<", end = ">", close = false, newline = true },
]
block_comment = ["<!--", "-->"]
